name: Build VS Code for macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install dependencies
        run: curl https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-10 

      - name: Environment
        run: env

      - uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode"
          ref: "fabdb6a30b49f79a7aba0f2ad9df9b399473380f"
          path: "vscode-source"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: npm install -g node-gyp

      - name: Install npm dependencies
        run: cd vscode-source && npm install

      - name: Build VS Code
        run: cd vscode-source && npm run gulp vscode-darwin-arm64

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_output
          path: .
