name: Build VS Code for macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode"
          ref: "fabdb6a30b49f79a7aba0f2ad9df9b399473380f"
          path: "vscode-source"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Test logs
        run: |
          echo "------"
          ls -ltrh
          echo "------"
          pwd
          echo "------"
          ls -ltrh ../

    # - name: Install dependencies
    #   run: |
    #     npm install -g node-gyp
    #     npm config set python python3

    # - name: Install npm dependencies
    #   run: npm install

    # - name: Build VS Code
    #   run: npm run gulp vscode-darwin-arm64

    # - name: Archive production artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: dist
    #     path: vscode/out
